name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o Sender sender/sender.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o Receive receiver/receiver.cpp

    - name: run
      run: ./Sender "sample-review/review-report.csv" 2 | ./Receive
      
    - name: build ReceiverTest
      run: g++ -Wall -Wextra -o Receive-test receiver-test/receiver-test.cpp receiver-test/functionsofreceiver.cpp
 

    - name: coverage report Sender
      run: gcov -r sender.cpp
      
    - name: coverage report Receiver
      run: gcov -r receiver.cpp
