name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
    
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o Sender sender/sender.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o Receive receiver/receiver.cpp

    - name: run
      run: ./Sender "sample-review/review-report.csv" 2 | ./Receive
      
    - name: static analysis
      run: cppcheck --enable=all --error-exitcode=1 -ireceiver-test/receiver-test.cpp -iSender-Test/SenderTest.cpp .
      
    - name: coverage report Sender
      run: gcov -r functionsofreceiver.cpp
      
    - name: build SenderTest
      run: g++ -Wall -Wextra -o Sender-test Sender-Test/*.cpp
      
    - name: run SenderTest
      run: ./Sender-test  
      
    - name: build ReceiverTest
      run: g++ -Wall -Wextra -o Receive-test receiver-test/*.cpp
      
    - name: run
      run: ./Receive-test

    
      
    - name: coverage report Receiver
      run: gcov -r receiver.cpp
